version: '3'
services:
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.09"
    command:
      ["/cloud_sql_proxy",
       "-instances=spinapptest-151310:us-central1:v3admin-sb-sql-master-002=tcp:0.0.0.0:3306",
       "-credential_file=/config/spinapptest.json"]
    ports:
      - "3306:3306"
    volumes:
      - "/Users/suzuki_shogo/Desktop/spinapptest.json:/config/spinapptest.json"

    # mysqlを使いたい場合
    # image: mysql:5.7
    # environment:
    #   MYSQL_ROOT_PASSWORD: root

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: web1
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "10080:80"
    depends_on:
      - web 
